### ISSUE TITLE
pg8000 can't handle freezegun's FakeDate/FakeDateTime types (maybe not freezegun's problem?)

### ISSUE THREAD

**Issue by gimbo** [spulec/freezegun#170]
I'm not sure if this really an issue with `freezegun` or `pg8000`, or if I'm doing something stupid, but I can't use `freezegun`-generated dates for insertions or selections in a postgres database using the `pg8000` interface.  (This works OK with `psycopg2` instead of `pg8000` however.)

I first came across this while writing integration tests for a Flask app using `flask-sqlalchemy`, but I've boiled it down to a simple example involving only `freezegun` and `pg8000` as follows.

Given a postgres database called `foo` with one table `foo` with one date column:

```
$ psql -U postgres foo 
psql (9.6.1)
Type "help" for help.

foo=# \d foo
    Table "public.foo"
 Column | Type | Modifiers 
--------+------+-----------
 when   | date | 
```

the following connects to it via `pg8000` and attempts to insert a row inside a `freezegun` context:

```
#!/usr/bin/env python

import datetime

from freezegun import freeze_time
import pg8000

conn = pg8000.connect(user='postgres', database='foo')
cursor = conn.cursor()
with freeze_time('2016-12-25'):
    today = datetime.date.today()
cursor.execute('INSERT INTO foo (when) VALUES (%s)', (today,))
```

and it fails with the following traceback:

```
Traceback (most recent call last):
  File "/home/gimbo/.virtualenvs/sqlwtf/lib/python3.5/site-packages/pg8000/core.py", line 1849, in make_params
    params.append(self.py_types[typ])
KeyError: <class 'freezegun.api.FakeDate'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gimbo/.virtualenvs/sqlwtf/lib/python3.5/site-packages/pg8000/core.py", line 1852, in make_params
    params.append(self.inspect_funcs[typ](value))
KeyError: <class 'freezegun.api.FakeDate'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./wtf8.py", line 12, in <module>
    cursor.execute('INSERT INTO foo (when) VALUES (%s)', (today,))
  File "/home/gimbo/.virtualenvs/sqlwtf/lib/python3.5/site-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "/home/gimbo/.virtualenvs/sqlwtf/lib/python3.5/site-packages/pg8000/core.py", line 1887, in execute
    params = self.make_params(args)
  File "/home/gimbo/.virtualenvs/sqlwtf/lib/python3.5/site-packages/pg8000/core.py", line 1855, in make_params
    "type " + str(e) + "not mapped to pg type")
pg8000.core.NotSupportedError: type <class 'freezegun.api.FakeDate'>not mapped to pg type
```

If I use `psycopg2` rather than `pg8000` it works OK, so maybe the problem is not really `freezegun`'s; OTOH maybe not, so I thought I'd raise it.

As a side note: I tried to get around this by having `freezegun` generate the frozen `FakeDate` and then constructing a "real" `datetime.date` from it piece by piece, but that fails because under `freezegun`, the `datetime.date()` constructor *always* returns a `FakeDate` - which goes beyond what I thought `freezegun` would do from reading its `README`.  That means I can never create an actual `datetime.date` while `freezegun` is in play, which seems problematic in itself to me.  For example:

```
ld0 $ python                                                   
Python 3.4.5 (default, Dec  1 2016, 20:09:55) 
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
Python shell history and tab completion are enabled.
>>> import datetime
>>> import freezegun
>>> with freezegun.freeze_time('2016-12-25'):
...     foo = datetime.date(2017, 1, 3)
...     bar = datetime.datetime(2017, 1, 3, 16, 10, 30)
... 
>>> foo
FakeDate(2017, 1, 3)
>>> bar
FakeDatetime(2017, 1, 3, 16, 10, 30)
```

**Comment by gimbo** [comment]
I probably should also have mentioned:

```
$ pip freeze
flake8==3.2.1
freezegun==0.3.8
mccabe==0.5.3
pg8000==1.10.6
psycopg2==2.6.2
pycodestyle==2.2.0
pyflakes==1.3.0
python-dateutil==2.6.0
six==1.10.0
SQLAlchemy==1.1.4
```

**Comment by gimbo** [comment]
Demo code repo: https://github.com/gimbo/freezegun_pg8000_bug

**Comment by spulec** [comment]
Hmmmm.

Two possible solutions:

1). It looks like pg8000 has a list of types that it can accept `self.py_types`. You could try appending the freezegun class to that list.

2). If you do `from freezegun.api import real_date`, you can get access to the real date module to do any casting you need.

Let me know if neither of those work. I can't think of a way to make this work by default.

**Comment by spulec** [comment]
Yeah, it seems like pg800 is going to complain unless we pass a real datetime. Due to how freezegun is implemented, I don't think this is going to be possible unfortunately.

**Comment by louischatriot** [comment]
@spulec First, thanks for this useful library. I don't agree though that pg8000 is at fault here, given there should be an implicit contract that freezegun will freeze time *without* changing object types with fake objects, otherwise this will cause unforeseen side effects (e.g. everytime some code check a `datetime`'s type). It's actually really surprising that psycopg2 doesn't complain!

I think it's actually possible to implement freezegun in this way, see the code below (only freezing `datetime.utwnow()` but can easily be generalized).

**fake_time.py**
```python
import datetime
import sys

real_datetime = datetime.datetime


def get_fake_datetime_class(frozen_datetime):
    class fake_datetime(datetime.datetime):
        def __new__(cls, *args, **kwargs):
            return real_datetime.__new__(real_datetime, *args, **kwargs)

        def utcnow(): return frozen_datetime
        # Also redefine all frozen datetime methods here to return frozen datetime objects
        # .
        # .
        # .

        def fromtimestamp(*args, **kwargs): return real_datetime.fromtimestamp(*args, **kwargs)
        # Also redefine all non-frozen datetime methods here to return datetime objects
        # .
        # .
        # .

    return fake_datetime


class freeze_time():
    def __init__(self, year, month, day, hour = 0, minute = 0, second = 0):
        self.frozen_datetime = real_datetime(year, month, day, hour, minute, second)

    def __enter__(self):
        # Memorize modified modules to clean state after use
        self.modified_modules = []

        for mod_name, module in list(sys.modules.items()):
            if (mod_name is None or module is None or mod_name == __name__
                    or mod_name.endswith('.six.moves')
                    or (not hasattr(module, "__name__"))
                    or module.__name__ in ('_datetime', 'datetime', 'time')):
                continue

            try:
                module_attributes = dir(module)
            except TypeError:
                module_attributes = []

            for attribute_name in module_attributes:
                try:
                    the_import = getattr(module, attribute_name)
                except (ImportError, AttributeError, TypeError):
                    continue
                else:
                    if (id(the_import) == id(real_datetime)):
                        self.modified_modules.append(module)
                        setattr(module, attribute_name, get_fake_datetime_class(self.frozen_datetime))

    def __exit__(self, exc_type, exc_value, traceback):
        for module in self.modified_modules:
            setattr(module, 'datetime', real_datetime)
```

**main.py**
```python
from fake_time import freeze_time
from datetime import datetime


print("No freeze")
print(datetime(2011,1,1))
print(type(datetime(2011,1,1)))
print(datetime.utcnow())
print(type(datetime.utcnow()))
print(datetime.fromtimestamp(213))
print(type(datetime.fromtimestamp(213)))


with freeze_time(2016, 5, 25, 1, 2, 33):
    print('')
    print("With freeze")
    print(datetime(2011,1,1))
    print(type(datetime(2011,1,1)))   # Constructor still returns a datetime object
    print(datetime.utcnow())
    print(type(datetime.utcnow()))    # utcnow() still returns a datetime object
    print(datetime.fromtimestamp(213))
    print(type(datetime.fromtimestamp(213)))   # Any method e.g. fromtimestamp still returns a datetime object
```

**Comment by spulec** [comment]
I believe the reason that psycopg2 (and most other ORMs) don't have an issue is because they are utilizing duck typing. Our `FakeDatetime` even satisfies an `isinstance(now, real_datetime)` check. From my investigation it seems that pg8000 decides to use `type(value)` and only matches exactly if it is a datetime.

While I would like it if we could utilize real datetime objects more, this implementation comes with some issues. For example I believe the following code will return the wrong result:

```python
with freeze_time(2016, 5, 25, 1, 2, 33):
    current_time = datetime.utcnow()
    print(current_time)  # 2016-05-25 01:02:33
    print(current_time.utcnow())  # 2018-03-08 15:06:08.818514
```

We could get around that by monkey-patching the returned real datetime, but that seems even more hacky.

Thoughts?

**Comment by louischatriot** [comment]
This is a hard problem indeed (your example is correct, I did not monkey patch the returned `datetime`), the porosity between static and dynamic methods in Python makes it really hard if impossible to reach a "perfect" solution (e.g. using `utcnow()` on a `datetime` instance feels very wrong to me).

That said, I still believe returning real objects is the best solution since there are modules that do not use duck typing - the code will be hacky but it already is quite hacky (I mean it's modifying already imported modules at runtime !).

In any case if you do not want to create the "perfect" solution (which I think is reasonable given it's going to be quite some work) I think this warrants at least a warning in the readme, either "be aware the objects returned are datetime-like but not real datetimes" or "the objects returned are real datetimes so datetimes generated from their `utcnow` will not be frozen"

Interesting problem in any case :)
