### ISSUE TITLE
Testing asyncio code made harder due to freezing time.monotonic()

### ISSUE THREAD

**Issue by romainletendart** [spulec/freezegun#383]
Hi,

Version 1.1.0 makes it harder to test asyncio-based code relying on `asyncio.sleep()`, `asyncio.wait_for()`, ... where what we only want to test is `datetime` related. In such cases, without any auto or manual ticking all time based awaits simply freeze because : 
`The event loop has its own internal clock for computing timeouts. Which clock is used depends on the (platform-specific) event loop implementation; ideally it is a monotonic clock. This will generally be a different clock than time.time().` (See https://docs.python.org/3.6/library/asyncio-eventloop.html#asyncio-delayed-calls).

Would it be possible to make time.monotonic() freezing optional?

**Comment by boxed** [comment]
Seems more like the solution is to add something to the whitelist? You can add your own whitelist and try it out!

**Comment by romainletendart** [comment]
Thanks @boxed for your answer.
I'm not sure how to proceed?
How do you provide such whitelist?

**Comment by boxed** [comment]
No, you want to put asyncio or something in the ignore list.

**Comment by romainletendart** [comment]
That indeed did the trick for me:
```python
with freezegun.freeze_time(dt, ignore=['asyncio']):
    # asyncio time-based code
```
Thank you very much!

**Comment by boxed** [comment]
That good but I don't think this means we should close the ticket? The question is if freezegun needs to have this in the ignore list or not. I don't think it's obvious. 

Could you maybe show a minimal program that shows this issue? I think this would help me understand if freezegun needs to be changed.

**Comment by tzoiker** [comment]
@boxed I have faced the very same problem, but in another context and it was very painful to debug. 

- I have used `aiormq` library to connect to RabbitMQ;
- It uses heartbeats to monitor connections and relies on monotonic time to check the time of a heartbeat;
- Using `freeze_time` in some tests lead to the following:
    - Last heartbeat was set to event loop time;
    - `freeze_time` patched monotonic time;
    - Difference between last heartbeat and the loop time became extremely large, leading to connection errors on tests teardown.

Some suggestions:
- Do not ever patch monotonic time **implicitly** for any module - it will most certainly break things. Adding asyncio to default ignore list will not help (there may be different event loop implementations) in all the cases which rely on continuous flow of monotonic time.
- Instead of ignoring specific modules, it should be possible to specify exactly what kind of "times" user wants to freeze, and once again, monotonic time should not be there by default.

Thank you for consideration.
