### ISSUE TITLE
Should sleep() change the frozen time?

### ISSUE THREAD

**Issue by AlexFinkel** [spulec/freezegun#47]
I'm interested in adding a feature for the sleep(seconds) built-in function being mocked to increment the frozen time by seconds. This simulates the affect of sleep in the real world, obviously without having to actually wait.

Would this violate the spirit of freezegun, or would you be likely to support such a feature?

**Comment by benkuhn** [comment]
I would be interested in implementing a mock for `sleep`--we have some integration tests that I'd love to be able to run `sleep` during rather than routing our code around the sleep calls when under test.

Just want to check how to do this before I dive in--the right thing to do here is to create a FakeSleep class analogous to FakeStrfTime, have its __call__ method move forward the `time_to_freeze` variable of the factory, and (if the parameter is supplied) patch it in everywhere the FakeStrfTime class is patched in?

**Comment by spulec** [comment]
I don't think that should require any changes to freezegun to make work. If you do the Raw use, then patch `sleep` to increment the `freezer.time_to_freeze`.

**Comment by jdunck** [comment]
I would argue for a back-channel way to advance time.  (Maybe also time.sleep should advance, but there should be a test-specific way to advance time as well.)  As an example, freezegun.warp(seconds).

@spulec I started a local branch to support time.sleep/freezegun.warp, but immediately ran into the fact that FakeTime is constructed with an actual time_to_freeze rather than a reference to the possibly-nested times_to_freeze.  What do you think about moving that FakeDateTime.times_to_freeze out to a thread-local stack that start/stop push and pop from?

**Comment by spulec** [comment]
@jdunck that sounds good. I think it would actually make a lot of things easier.

**Comment by arnuschky** [comment]
A `freezegun.warp(seconds)` would be awesome! :+1:

**Comment by arnuschky** [comment]
What I currently use as an intermediary (ugly) hack:

```
        now = datetime.now()
        # do something

        now += timedelta(seconds=0.3)
        with freeze_time(now):
             # do something 0.3 secs later

        now += timedelta(seconds=0.4)
        with freeze_time(now):
             # do something 0.4 secs later again
```

**Comment by vartec** [comment]
I've worked around the issue by doing this:
```
    @mock.patch('time.sleep')
    def test_timeout(self, mock_sleep):
        with freeze_time() as frozen_time:
            mock_sleep.side_effect = lambda seconds: frozen_time.tick(timedelta(seconds=seconds))
            ...
```

**Comment by spulec** [comment]
Going to close in favor of https://github.com/spulec/freezegun/issues/142

**Comment by raylu** [comment]
what is #142? there is no such issue
