### ISSUE TITLE
1.3.0: `freezegun/__init__.py` is missing new version number

### ISSUE THREAD

**Issue by mtelka** [spulec/freezegun#520]
The tagged `freezegun/__init__.py` contains [obsolete version number](https://github.com/spulec/freezegun/blob/1.3.0/freezegun/__init__.py).  This causes inconsistent installation when attempted to install from github tarball.

**Comment by bblommers** [comment]
Thanks for letting us know @mtelka. I made a mistake with the ordering; [the version increase should obviously happen before the tagging action](https://github.com/spulec/freezegun/commit/ff98d1ff018ac1105bb151758e5609872a02f8bb).

This has been [fixed in 1.3.1](https://github.com/spulec/freezegun/blob/1.3.1/freezegun/__init__.py).
